### PR TITLE
Modify attributes names for atomic property

### PR DESCRIPTION
**Pull request by gabrielasd**
The changes intend to make the names of the properties consistent within our package and with other QC-Devs packages. 
For example the attributes `natom`, for the atomic number, and `mass` were changed to `atnum`,  and `atmass`, respectively, as is used in IOData.

### CODE REVIEW

**Comment by gabrielasd** [comment]
I've updates most compilation and test files. Next I'll fix code dealing with the promolecule functionality.

**Comment by gabrielasd** [comment]
I've finalized the updates to the modules after the change to the SpeciesData attributes.

The test that donesn't pass from the github workflow, for ubuntu OS with python 3.7, is because of the numpy.testing module in the promolecule tests. This is already fixed by the changes in PR #49 which haven't been merged, so I left it unmodified here.

**Review by msricher — APPROVED** [review]
It looks good to me.

**Review by marco-2023 — APPROVED** [review]
I added a commit to solve the merge conflicts I think it is ready to be merged. @gabrielasd can you take a last look to the changes I introduced to solve the merge conflicts?

**Pull request merged**
