### PR TITLE
Support promolecules with single atom

### LINKED ISSUE #134: Support promolecules with only one atom
When a promolecule has only one atom, specified by an array with one fewer dimension than expected, we should still be able to build the pro-atom density (centered on a point of interest). I.e., it is a bit unpleasant that one has to do things like

`atomdb.make_promolecule(mol.atnums[i,np.newaxis], mol.atcoords[i, np.newaxis], dataset=dataset)`

### PR DESCRIPTION
**Pull request by msricher**
Fixes #134

### CODE REVIEW

**Review by PaulWAyers — APPROVED** [review]
Thanks @msricher . I'd like to get @marco-2023 and/or @gabrielasd 's feedback too, but it looks good to me.

**Review by PaulWAyers — COMMENTED** [review]
Don't we need to do the same trick for charges/mults in lines 582-592?

**Comment by msricher** [comment]
Yep you're right. I didn't think about both of those also being single values.

**Review by PaulWAyers — APPROVED** [review]
Looks good to me. @marco-2023  and/or @gabrielasd

**Review by gabrielasd — CHANGES_REQUESTED** [review]
Changes look good to me too.

@msricher could you add a test case for this fix to [test_promolecule.py](https://github.com/theochem/AtomDB/blob/master/atomdb/test/test_promolecule.py)
It could be a slight change of this test case in the module:
https://github.com/theochem/AtomDB/blob/abf1008b88b89f3387c7c3559c3efa7bd6de93da/atomdb/test/test_promolecule.py#L83-L88

**Comment by gabrielasd** [comment]
I don't think this is related to the changes Michelle introduced, but the CI checks are failing when building the website.

It mentions an incompatibility between Scipy library and python version. This doesn't make sense to me since the rest of the checks for different python envs are passing. 
It could be that the Scipy version listed [here](https://github.com/theochem/AtomDB/blob/master/website/requirements.txt) differs from the one in the [pyproject.toml](https://github.com/theochem/AtomDB/blob/master/pyproject.toml), but I am not sure.

@msricher  or @marco-2023 could you look into this?

**Comment by FanwangM** [comment]
I am not familiar with the technical part, but the failing test is fixed now.

**Comment by PaulWAyers** [comment]
We used to limit the top version of Scipy because we were using its old-fashioned generalized inverse. We don't use that anymore (and probably not at all in this package) so this is a good update on the dependencies.

**Review by gabrielasd — APPROVED** [review]

**Pull request merged**
